### ISSUE TITLE
Volume % incorrect for Onkyo AVRs

### ISSUE THREAD

**Issue by mlamoure** [FlyingDiver/Indigo-HA-Agent#11]
The slider bar is controlling the AVR 0 - 40% (Sliding the bar to 100% in indigo drives a level 40/100 on my AVR)

This is the output of the logging when the AVR is set to 100% from outside of Indigo:

```
"onkyo_avr_main_level_living_room": {
            "attributes": {
                "friendly_name": "Onkyo AVR - Main Level Living Room",
                "is_volume_muted": false,
                "media_content_id": "",
                "media_duration": 0,
                "media_track": 0,
                "repeat": "off",
                "shuffle": false,
                "sound_mode_list": [
                    "FactoryDefaults"
                ],
                "supported_features": 479807,
                "volume_level": 0.82
            },
            "context": {
                "id": "01HS1FVWRQAQJ6SA2Q7KJ3F5VE",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "media_player.onkyo_avr_main_level_living_room",
            "last_changed": "2024-03-15T16:35:00.671789+00:00",
            "last_updated": "2024-03-15T16:42:02.903834+00:00",
            "state": "idle"
        },
```

>
 Script
```
address : media_player.onkyo_avr
batteryLevel : None
blueLevel : None
brightness : 100
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
defaultBrightness : 100
description : 
deviceTypeId : ha_media_player
displayStateId : brightnessLevel
displayStateImageSel : NoImage
displayStateValRaw : 100
displayStateValUi : 100
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 0
globalProps : MetaProps : (dict)
     no.homeassistant.plugin : (dict)
          SupportsOff : true (bool)
          SupportsOn : true (bool)
          SupportsPlay : true (bool)
          SupportsPlayMedia : true (bool)
          SupportsSelectSource : true (bool)
          SupportsSetVolume : true (bool)
          SupportsStatusRequest : false (bool)
          SupportsVolumeMute : true (bool)
          SupportsVolumeStep : true (bool)
          address : media_player.onkyo_avr (string)
          states_list : (list)
               Item : source_list (string)
               Item : volume_level (string)
               Item : is_volume_muted (string)
               Item : source (string)
               Item : audio_information (string)
               Item : video_information (string)
               Item : video_out (string)
               Item : friendly_name (string)
               Item : supported_features (string)
greenLevel : None
id : 294427042
lastChanged : 2024-03-15 12:39:09
lastSuccessfulComm : 2024-03-15 12:39:09
ledStates : []
model : Home Assistant Media Player
name : Living Room Onkyo
onBrightensToDefaultToggle : False
onBrightensToLast : False
onState : True
ownerProps : no.homeassistant.plugin : (dict)
     SupportsOff : true (bool)
     SupportsOn : true (bool)
     SupportsPlay : true (bool)
     SupportsPlayMedia : true (bool)
     SupportsSelectSource : true (bool)
     SupportsSetVolume : true (bool)
     SupportsStatusRequest : false (bool)
     SupportsVolumeMute : true (bool)
     SupportsVolumeStep : true (bool)
     address : media_player.onkyo_avr (string)
     states_list : (list)
          Item : source_list (string)
          Item : volume_level (string)
          Item : is_volume_muted (string)
          Item : source (string)
          Item : audio_information (string)
          Item : video_information (string)
          Item : video_out (string)
          Item : friendly_name (string)
          Item : supported_features (string)
pluginId : no.homeassistant.plugin
pluginProps : emptyDict : (dict)
protocol : Plugin
redLevel : None
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     actual_state : on (string)
     audio_information : {"format": "PCM", "input_frequency": "44.1 kHz", "input_channels": "2.0 ch", "listening_mode": "All Ch Stereo", "output_channels": "4.0 ch", "output_frequency": ""} (string)
     brightnessLevel : 100 (integer)
     friendly_name : onkyo_avr (string)
     is_volume_muted : false (bool)
     lastUpdated : 2024-03-15T16:39:09.210399+00:00 (string)
     onOffState : on (on/off bool)
     source : Sonos (string)
     source_list : ["JAP Matrix", "Sonos", "AppleTV", "Roku"] (string)
     supported_features : 20364 (integer)
     video_information : {"input_resolution": "Unknown", "input_color_schema": "", "input_color_depth": "24bit", "output_resolution": "0 x 0p", "output_color_schema": "", "output_color_depth": "24bit", "picture_mode": ""} (string)
     video_out : yes,out (string)
     volume_level : 2.05 (real)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsColor : False
supportsOnState : True
supportsRGB : False
supportsRGBandWhiteSimultaneously : False
supportsStatusRequest : False
supportsTwoWhiteLevels : False
supportsTwoWhiteLevelsSimultaneously : False
supportsWhite : False
supportsWhiteTemperature : False
version : None
whiteLevel : None
whiteLevel2 : None
whiteTemperature : None
```

**Comment by FlyingDiver** [comment]
Check the max_volume setting for your Onkyo in HA.  It's acting like that's set to 40%

**Comment by FlyingDiver** [comment]
https://www.home-assistant.io/integrations/onkyo/

**Comment by FlyingDiver** [comment]
I'm converting from Indigo's 0-100 scale to HA's 0-1 scale, so there's probably something weird going on in the Onkyo integration.

**Comment by mlamoure** [comment]
I'm having trouble figuring this out.  The scale is way off at the moment.  My primary listening volumes are all above 100 on the Indigo slider.

<img width="1512" alt="Screenshot 2024-04-05 at 5 35 09 PM" src="https://github.com/FlyingDiver/Indigo-HA-Agent/assets/1021890/d5891dce-5450-44d4-8a7c-d55f97d20625">

**Comment by FlyingDiver** [comment]
When you use the volume control on the AVR itself, what's the range on the display?  Min 0, max ??

I see from the custom states list that HA is reporting the volume_level as 1.06, which I didn't think was possible.  I thought the max was 1.0.  I think it's doing that because the max_volume in the config is wrong.

I won't be able to spend any time on this until mid week.  But when I do, I'd like to see the debug output of the plugin when you set the volume using (1) physical volume control, (2) HA slider control, and (3) Indigo control.  For zero volume, 50% volume, and 100% volume.

**Comment by mlamoure** [comment]
Sure thing.  I refrain from posting while I investigate the behavior using a few different settings on the HA side.  Then I'll post your scenarios as you requested.  Thanks for the troubleshooting support.

**Comment by FlyingDiver** [comment]
A few more thoughts before you start testing.  In the HA config, set max_volume to 100.  That value is used to scale the HA UI slider to the volume control, to prevent the UI from going over a set percentage actual volume.  I think that's an HA UI tweak only,  so you don't want to use it for now.

Second, I think receiver_max_volume needs to be set to whatever the max volume number is on the actual volume control.  The notes I saw indicated that it's 82 for some models, but goes to over 200 for others.

**Comment by mlamoure** [comment]
I played with this a bit more today.  max_volume at 82 and receiver_max_volume at 82 are the setting where the HA volume slider value and my actual AVR are showing the same volume level.

Would you prefer I share the debug logs you requested with max_volume at 100 or 82?

**Comment by FlyingDiver** [comment]
With those settings, does it work the way you would expect?  If so, I'm not sure there's anything else to be done.

**Comment by mlamoure** [comment]
Yes, we can close.  I can access a wide enough range of volume levels using HA and the plugin now.  The correct settings for me ended up being:

media_player:
  - platform: onkyo
    host: 10.66.0.51
    name: onkyo_avr
    max_volume: 100
    receiver_max_volume: 175

What ended up taking so long is that I was testing incorrectly.  I had a DLNA instance of my AVR which I believe I accidentally tested using, rather than the Onkyo plugin device.  Also, the Onkyo plugin seems dated, and the quick YAML reload doesn't take proper effect.  You have to fully restart HA.
