### ISSUE TITLE
Missing media_player states when device is powered down

### ISSUE THREAD

**Issue by mlamoure** [FlyingDiver/Indigo-HA-Agent#12]
I make extensive use the Timed Devices and Group Change Listener plugin in my setup.  One example is that I trigger volume changes to my second AV zone based on changes to the volume in Zone 1.

The Timed Devices plugin monitors a state and configures timers around it.  In this example, I'm monitoring for when the state changes pause for a certain amount of time, in order to not fire the action multiple times repeatedly.  

In the previous example, it's monitoring volume_level.  

However, when the media_device is off, these states are missing from the states dictionary, and these plugins throw errors:

`   Timed Devices Error             "House AV - Main area volume change" thread error 
'key volume_level not found in dict'
`

Is there a way that these standard states could persist to avoid these errors?

**Comment by FlyingDiver** [comment]
I'm probably not going to do that.  if I did, there would be no way to get rid of old states and no way to know what states are current (and valid) and which are not.

Let me see if I can figure out an alternative.

**Comment by mlamoure** [comment]
I suggest hold til we resolve the volume issue.  My suspicion is that this is not causing an issue other than a temporary error to the log.  The Timed Devices plugin does not misbehave, it picks up normal operations after posting the error.

**Comment by mlamoure** [comment]
I'll live with this.
