### ISSUE TITLE
Support for generic commands for Fan Devices

### ISSUE THREAD

**Issue by mlamoure** [FlyingDiver/Indigo-HA-Agent#15]
Feature Request -- I would like to be able to send raw commands on the speed level for fan devices.  This way you can give control to the end user for controlling the speed for various different fans which may have more than four speed levels which the Indigo UI supports.

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-HA-Agent/releases/tag/2024.0.3

Test as many of the fan commands as you can.

**Comment by mlamoure** [comment]
To confirm, you added the "Home Assistant Agent Actions" -> "Set Fan Speed", "Direction", "Preset Mode", "Oscillate"?

**Comment by FlyingDiver** [comment]
Just set speed is new.  The others were already there (but might not have had "Fan" in the name).

**Comment by mlamoure** [comment]
Testing now via the UI.  Eventually I'd like to move this into my own python script.  Can you help fix what's wrong with this?

```
pluginID = "no.homeassistant.plugin"
plugin = indigo.server.getPlugin(pluginID)
plugin.executeAction("set_fan_speed_action", deviceId=fan.fanId, props={'speed':str(convert_baf_speed_levels_to_percentage[target_speed])})
```

**Comment by FlyingDiver** [comment]
fan.devID?

**Comment by mlamoure** [comment]
No that's a long working property of my own custom class.  Here's what the log is spitting out:

```
   Script Error                    trigger "Auto fan" script error in file auto_fan.py:
   Script Error                    plugin does not have a <CallbackMethod> specified for action id set_fan_speed_action
   Script Error                    Exception Traceback (most recent call shown last):

     auto_fan.py, line 898, at top level
     auto_fan.py, line 853, in AutoComfort
InvalidAction: plugin does not have a <CallbackMethod> specified for action id set_fan_speed_action

```

**Comment by FlyingDiver** [comment]
```
pluginID = "no.homeassistant.plugin"
plugin = indigo.server.getPlugin(pluginID)
plugin.executeAction("set_fan_speed", deviceId=fan.fanId, props={'speed':str(convert_baf_speed_levels_to_percentage[target_speed])})
```

You need to specify the id of the action (in Actions.xml) not the method name.

**Comment by mlamoure** [comment]
Ah, thank you.  So far testing looks to be going well.  For the BAF the "steps" are 14.29% per increment, since 7 does not divide into 100 evenly.  Either your plugin or the BAF HA plugin seems to make this easy enough, though.  If I send 42% to HA, it puts it on step 3, even though the exact number would be 42.87.  Also the "percentage" custom state that your plugin picks up is also nicely rounded.  This could have made my life a lot harder.

In the Indigo UI, I'd recommend changing the HVAC fan mode to avoid confusion.

I can post back in a few hours with a "all clear" once I test some more.

**Comment by FlyingDiver** [comment]
Yeah, the names are confusing.  I can update the name without changing the ID and it won't break anything.

The round-off is happening in the HA integration.  My fan has 6 steps (16.66%) and it always picks the one closest to the value selected.

**Comment by mlamoure** [comment]
I think you are safe to release.  Thanks again for the support.
