### ISSUE TITLE
state key actual_state not defined (ignoring update request)

### ISSUE THREAD

**Issue by akataz04** [FlyingDiver/Indigo-HA-Agent#2]
HA Climate and Value Sensor entities devices generate the error "state key actual_state not defined (ignoring update request)" sporadically.  Reboot the plugin, the issue resolves for a day or so, then restarts.

**Comment by EagleDTW** [comment]
Thanks, Joe!

-Daniel



            "foobot_daniel_s_iaq_co2": {
            "attributes": {
                "friendly_name": "Foobot CO2",
                "icon": "phu:co2",
                "unit_of_measurement": "ppm"
            },
            "context": {
                "id": "01HBVQF3VGV3YJZCVCBBCQAK6V",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.foobot_daniel_s_iaq_co2",
            "last_changed": "2023-10-03T21:35:22.480280+00:00",
            "last_updated": "2023-10-03T21:35:22.480280+00:00",
            "state": "1643.7"
        },
        "foobot_daniel_s_iaq_humidity": {
            "attributes": {
                "friendly_name": "Foobot Humidity",
                "icon": "phu:moisture",
                "unit_of_measurement": "%"
            },
            "context": {
                "id": "01HBVQF3VGE5EH5N51XKSS7QTM",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.foobot_daniel_s_iaq_humidity",
            "last_changed": "2023-10-03T21:35:22.480238+00:00",
            "last_updated": "2023-10-03T21:35:22.480238+00:00",
            "state": "53.4"
        },
        "foobot_daniel_s_iaq_index": {
            "attributes": {
                "friendly_name": "Foobot AQI",
                "icon": "mdi:air-filter",
                "unit_of_measurement": "%"
            },
            "context": {
                "id": "01HBVQF3VG5JVD5RPXR0NDGWY7",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.foobot_daniel_s_iaq_index",
            "last_changed": "2023-10-03T21:35:22.480368+00:00",
            "last_updated": "2023-10-03T21:35:22.480368+00:00",
            "state": "58.3"
        },
        "foobot_daniel_s_iaq_pm2_5": {
            "attributes": {
                "friendly_name": "Foobot pm2.5",
                "icon": "mdi:cloud",
                "unit_of_measurement": "\u00b5g/m\u00b3"
            },
            "context": {
                "id": "01HBVQF3VF903W2A18Z04BHPZC",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.foobot_daniel_s_iaq_pm2_5",
            "last_changed": "2023-10-03T21:35:22.479966+00:00",
            "last_updated": "2023-10-03T21:35:22.479966+00:00",
            "state": "20.5"
        },
        "foobot_daniel_s_iaq_temperature": {
            "attributes": {
                "device_class": "temperature",
                "friendly_name": "Foobot Temp",
                "icon": "mdi:home-thermometer-outline",
                "unit_of_measurement": "\u00b0F"
            },
            "context": {
                "id": "01HBVQF3VG3Q5WFVYSCQNH9FNH",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.foobot_daniel_s_iaq_temperature",
            "last_changed": "2023-10-03T21:35:22.480169+00:00",
            "last_updated": "2023-10-03T21:35:22.480169+00:00",
            "state": "76.8"
        },
        "foobot_daniel_s_iaq_voc": {
            "attributes": {
                "friendly_name": "Foobot VOC",
                "icon": "phu:voc",
                "unit_of_measurement": "ppb"
            },
            "context": {
                "id": "01HBVQF3VGSKAC2J6SVPTZST87",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.foobot_daniel_s_iaq_voc",
            "last_changed": "2023-10-03T21:35:22.480326+00:00",
            "last_updated": "2023-10-03T21:35:22.480326+00:00",
            "state": "453.7"
        },

**Comment by FlyingDiver** [comment]
Should be fixed in 2023.1.0.  Reopen if not.
