### ISSUE TITLE
Request to bring updated Door/Window sensor states to Indigo

### ISSUE THREAD

**Issue by IndigoColly** [FlyingDiver/Indigo-HA-Agent#4]
Is it possible to bring a door/window sensor through with states "Open" and "Closed" instead of "On" and "Off"?

**Comment by FlyingDiver** [comment]
Not really, since Indigo doesn't have a "cover" device with open/closed states.  So this plugin does the convention  of open=on.  But it might be possible to show Open/Closed in the State column in the ui.  I'll look at that.

**Comment by FlyingDiver** [comment]
OK, just to be clear, you're talking about an HA binary sensor that's attached to a door or window for open/close status only, right?  Not a "cover" that controls a window shade or similar?

If so, can you run the "Write Home Assistant entity..." menu command in the Indigo Plugin menu, find the sensor you're talking about, and paste the info into a reply here?  It's look something like:
```
        "4_in_1_sensor_tampering_product_cover_removed": {
            "attributes": {
                "device_class": "tamper",
                "friendly_name": "4-in-1 Sensor Tampering, product cover removed"
            },
            "context": {
                "id": "01HCQJKP3ERSGA3TN666RR4BWJ",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "binary_sensor.4_in_1_sensor_tampering_product_cover_removed",
            "last_changed": "2023-10-14T17:09:13.454829+00:00",
            "last_updated": "2023-10-14T17:09:13.454829+00:00",
            "state": "off"
        },```

**Comment by FlyingDiver** [comment]
I have to find something in the data I'm getting back from HA that I can use to identify this as an open/close sensor.

**Comment by IndigoColly** [comment]
Sorry Joe I missed these comments as I was on holidays for a little.
For the Shelly sensor I get the following in the log:
`        "shelly_blu_door_window_6735_battery": {
            "attributes": {
                "device_class": "battery",
                "friendly_name": "Shelly BLU Door/Window 6735 Battery",
                "state_class": "measurement",
                "unit_of_measurement": "%"
            },
            "context": {
                "id": "01HCHCWPRXCXV8P961E8W3JCZC",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.shelly_blu_door_window_6735_battery",
            "last_changed": "2023-10-12T07:33:51.005305+00:00",
            "last_updated": "2023-10-12T07:33:51.005305+00:00",
            "state": "100"
        },
        "shelly_blu_door_window_6735_illuminance": {
            "attributes": {
                "device_class": "illuminance",
                "friendly_name": "Shelly BLU Door/Window 6735 Illuminance",
                "state_class": "measurement",
                "unit_of_measurement": "lx"
            },
            "context": {
                "id": "01HDR77JRJ307WT2XN3NRBWS7Y",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.shelly_blu_door_window_6735_illuminance",
            "last_changed": "2023-10-27T09:25:18.738849+00:00",
            "last_updated": "2023-10-27T09:25:18.738849+00:00",
            "state": "8.0"
        },
        "shelly_blu_door_window_6735_rotation": {
            "attributes": {
                "friendly_name": "Shelly BLU Door/Window 6735 Rotation",
                "state_class": "measurement",
                "unit_of_measurement": "\u00b0"
            },
            "context": {
                "id": "01HCHCWPRY1D75FFMD9PGMNER0",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.shelly_blu_door_window_6735_rotation",
            "last_changed": "2023-10-12T07:33:51.006386+00:00",
            "last_updated": "2023-10-12T07:33:51.006386+00:00",
            "state": "0.0"
        },
`

**Comment by IndigoColly** [comment]
Think it displays better without use of code tag.
        "shelly_blu_door_window_6735_battery": {
            "attributes": {
                "device_class": "battery",
                "friendly_name": "Shelly BLU Door/Window 6735 Battery",
                "state_class": "measurement",
                "unit_of_measurement": "%"
            },
            "context": {
                "id": "01HCHCWPRXCXV8P961E8W3JCZC",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.shelly_blu_door_window_6735_battery",
            "last_changed": "2023-10-12T07:33:51.005305+00:00",
            "last_updated": "2023-10-12T07:33:51.005305+00:00",
            "state": "100"
        },
        "shelly_blu_door_window_6735_illuminance": {
            "attributes": {
                "device_class": "illuminance",
                "friendly_name": "Shelly BLU Door/Window 6735 Illuminance",
                "state_class": "measurement",
                "unit_of_measurement": "lx"
            },
            "context": {
                "id": "01HDR77JRJ307WT2XN3NRBWS7Y",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.shelly_blu_door_window_6735_illuminance",
            "last_changed": "2023-10-27T09:25:18.738849+00:00",
            "last_updated": "2023-10-27T09:25:18.738849+00:00",
            "state": "8.0"
        },
        "shelly_blu_door_window_6735_rotation": {
            "attributes": {
                "friendly_name": "Shelly BLU Door/Window 6735 Rotation",
                "state_class": "measurement",
                "unit_of_measurement": "\u00b0"
            },
            "context": {
                "id": "01HCHCWPRY1D75FFMD9PGMNER0",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.shelly_blu_door_window_6735_rotation",
            "last_changed": "2023-10-12T07:33:51.006386+00:00",
            "last_updated": "2023-10-12T07:33:51.006386+00:00",
            "state": "0.0"
        },

**Comment by FlyingDiver** [comment]
huh. It's not a binary sensor.  It's a rotation sensor with the state in degrees of rotation.  That's not something I can convert to binary.

**Comment by IndigoColly** [comment]
I was surprised by that too.. It does display in HA as Door/Window sensor with Open and Closed states.

**Comment by FlyingDiver** [comment]
Does that use a Specific Shelly integration?  Because that would be able to customize the output.  Does it work with any of the Indigo Shelly plugins?

**Comment by IndigoColly** [comment]
![Screenshot 2023-11-05 at 22 59 16](https://github.com/FlyingDiver/Indigo-HA-Agent/assets/37013654/7bdca74e-118f-4f20-9ef6-cd7cd424bd9c)

**Comment by IndigoColly** [comment]
I think it is a specific Shelly integration. Not yet supported by the Shelly plugins but will bring it up with Aaron at some stage. Thought the HAA plugin might be the easier route in to Indigo.

**Comment by IndigoColly** [comment]
I dug deeper..... There was a lot in the log output.

        "shelly_blu_door_window_6735_window": {
            "attributes": {
                "device_class": "window",
                "friendly_name": "Office Window"
            },
            "context": {
                "id": "01HDR77JRH9ZD5SW4Q3NX4ZD6W",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "binary_sensor.shelly_blu_door_window_6735_window",
            "last_changed": "2023-10-27T09:25:18.737628+00:00",
            "last_updated": "2023-10-27T09:25:18.737628+00:00",
            "state": "off"
        },

**Comment by FlyingDiver** [comment]
Unfortunately, there's nothing that that identifies the sensor as belonging to a specific device class that can be converted.  It only has the entity ID for that sensor.  If you had two of them, there would be no way to tell they're both the same type of device.  It's a really poorly done integration in that regard.

**Comment by IndigoColly** [comment]
Just checking if my last message collided with yours.
It is being identified as "device_class": "window"

**Comment by FlyingDiver** [comment]
AH, that one you can use.

**Comment by FlyingDiver** [comment]
Is the window open or closed (when the state is "off")?

**Comment by FlyingDiver** [comment]
NVM, found it in the docs.

**Comment by FlyingDiver** [comment]
Try the latest commit:  https://github.com/FlyingDiver/Indigo-HA-Agent/archive/refs/heads/master.zip

**Comment by IndigoColly** [comment]
Works perfectly. Thanks for your efforts again.

**Comment by FlyingDiver** [comment]
In 2023.2.1.
