### ISSUE TITLE
Errors in log and values not transferring between HA and Indigo

### ISSUE THREAD

**Issue by EagleDTW** [FlyingDiver/Indigo-HA-Agent#5]
Hi Joe,

HA plugin errors:
   Error                           device "Jewish Date" state key sensorValue not defined
   Error                           device "Jewish Date" state key sensorValue not defined
   Error                           device "Jewish Parshat" state key sensorValue not defined
   Error                           device "Jewish Parshat" state key sensorValue not defined
   Error                           device "Jewish Holiday" state key sensorValue not defined
   Error                           device "Jewish Holiday" state key sensorValue not defined
   Error                           device "Jewish Date" state key sensorValue not defined
   Error                           device "Jewish Date" state key sensorValue not defined
   Error                           device "US AQI" state key sensorValue not defined
   Error                           device "US AQI" state key sensorValue not defined
   Error                           device "Foobot AQI" state key sensorValue not defined
   Error                           device "Foobot AQI" state key sensorValue not defined
   Error                           device "RealFeel Temp" state key sensorValue not defined
   Error                           device "RealFeel Temp" state key sensorValue not defined
   Error                           device "Arm&Disarm" state key onOffState not defined
   Error                           device "Arm&Disarm" state key onOffState not defined

Action Collection Error state id (sensorValue) isn't available for device model Home Assistant sensor - action not configured correctly

*And this warning when Insteon button press:
Received INSTEON "Atrium Light Master" on
Home Assistant Agent Warning Websocket unknown message type: {"id": 1, "type": "event", "event": {"event_type": "insteon.button_on", "data": {"address": "451a", "group": 1}, "origin": "LOCAL", "time_fired": "2023-10-04T17:12:56.075133+00:00", "context": {"id": "01HBXTV9GB7W383KTHZS", "parent_id": null, "user_id": null}}}

The log files contain extremely sensitive data and I dare not post it straight to Forums or Github, how should we arrange for you to receive them?

Thanks,
Daniel

**Comment by EagleDTW** [comment]
Hi Joe,

Is there a way to DM you without posting to the community?

Thank you,
Daniel

**Comment by FlyingDiver** [comment]
What version of the plugin was this?

**Comment by FlyingDiver** [comment]
You can DM me on the Indigo Forums and i'll send you my email.

**Comment by EagleDTW** [comment]
> What version of the plugin was this?

This was the beta right after the first release

**Comment by FlyingDiver** [comment]
Is this reproducable with the current release (2023.0.6) ? Or the available pre-release (2023.1.0)?

**Comment by EagleDTW** [comment]
Hi @FlyingDiver "Joe",

Following up in this thread...The sensor Value passed by the HA sensors seems to be a default 0 and thus gets processed wrong by downstream file scripts trying to convert the value to some form of date manipulation I do. It would be helpful if the actual value (pic below) is what was used for the sensor device value rather than the sensor value because this just appears to be wrong across all the devices.

Thank you,
Daniel
![Screenshot 2023-10-27 at 10 55 46 AM](https://github.com/FlyingDiver/Indigo-HA-Agent/assets/62778358/4b0514a4-c6aa-4b03-8e5f-9d971292d47d)

**Comment by EagleDTW** [comment]
Also Input_boolean is a toggle that is not like a binary sensor that gets updated with state values only, but is able to change the state of the helper in HA and as such needs to be accessible in Indigo as a device that can be turned on from the actions section with device light/appliance turn on/off calls (but currently isn't present - like it was in the old plugin design).

**Comment by FlyingDiver** [comment]
The only way you could have a sensorValue for that holiday entity is if you created is as a generic, then changed it to value sensor.  Don't do that.  Change it back.  And if it's still showing a sensor value, delete it and re-create it.  That's not a valid sensor entity and you can't force it to be.

**Comment by FlyingDiver** [comment]
> Also Input_boolean is a toggle that is not like a binary sensor that gets updated with state values only, but is able to change the state of the helper in HA and as such needs to be accessible in Indigo as a device that can be turned on from the actions section with device light/appliance turn on/off calls (but currently isn't present - like it was in the old plugin design).

I need to see the entity info for that device from the menu command.

**Comment by EagleDTW** [comment]
Strange that another input boolean "babysitter" works correctly with the 

> The only way you could have a sensorValue for that holiday entity is if you created is as a generic, then changed it to value sensor. Don't do that. Change it back. And if it's still showing a sensor value, delete it and re-create it. That's not a valid sensor entity and you can't force it to be.

I either get an error that sensor Value is not available if I create it as Generic Sensor or I get 0 in sensor value if I create it as a sensor Value straight from the menu instead of choosing generic category.

**Comment by EagleDTW** [comment]
> > Also Input_boolean is a toggle that is not like a binary sensor that gets updated with state values only, but is able to change the state of the helper in HA and as such needs to be accessible in Indigo as a device that can be turned on from the actions section with device light/appliance turn on/off calls (but currently isn't present - like it was in the old plugin design).
> 
> I need to see the entity info for that device from the menu command.

I think in the working path that I have for another similar device that I go the opposite direction and share a virtual device back to HA through Hassbridge and then use an automation on that end to link it to the actions needed, so deprecated implementation probably not needed!

**Comment by FlyingDiver** [comment]
I repeat:  I need to see the entity info for that device from the menu command.  For all the devices you don't think are working as they should.

Also, A Generic Device is NOT a sensor.  It's never going to have a sensorValue.  

If that device is actually in the sensors list, and sensorValue is wrong, then see paragraph 1.

**Comment by EagleDTW** [comment]
"havdalah_time": {
            "attributes": {
                "device_class": "timestamp",
                "friendly_name": "havdalah_time"
            },
            "context": {
                "id": "01HDQ1WMK2W0BD50PMVFBDT5JW",
                "parent_id": null,
                "user_id": null
            },
            "entity_id": "sensor.havdalah_time",
            "last_changed": "2023-10-26T22:32:42.850234+00:00",
            "last_updated": "2023-10-26T22:32:42.850234+00:00",
            "state": "2023-10-29T01:54:00+00:00"
        },

**Comment by EagleDTW** [comment]
> I repeat: I need to see the entity info for that device from the menu command. For all the devices you don't think are working as they should.
> 
> Also, A Generic Device is NOT a sensor. It's never going to have a sensorValue.
> 
> If that device is actually in the sensors list, and sensorValue is wrong, then see paragraph 1.

![Screenshot 2023-10-27 at 1 57 13 PM](https://github.com/FlyingDiver/Indigo-HA-Agent/assets/62778358/d6269bc8-6687-4ccc-ad9a-759d93771bfa)

**Comment by EagleDTW** [comment]
I can also delete and create it as a sensor Value if that is more appropriate? but that then comes up with 0 I'll do that and screen shot!
![Screenshot 2023-10-27 at 2 02 50 PM](https://github.com/FlyingDiver/Indigo-HA-Agent/assets/62778358/3f530a4b-54b5-4fcc-ad28-f9f3eed7200b)

**Comment by FlyingDiver** [comment]
Ok, that is the most bizarre thing I've ever seen.  A DATETIME object is classified as a sensor?  WTF?

But it's there, so I'll deal with it.  Unfortunately, Indigo sensors can't do strings as their value.  Not possible.  So the best I can do is make the sensorValue the epoch value (seconds since epoch) and the UI value the data string.  Should the UI value be the encoded string (2023-10-29T01:54:00+00:00) or the human formatted string (29 OCT 2023 1:54am UTC)?

**Comment by FlyingDiver** [comment]
Or better to just disallow it as a sensor and force it to Generic, you use the state to pick up the timestamp and deal with it?

**Comment by FlyingDiver** [comment]
What about the other one?  boolean_input?

**Comment by FlyingDiver** [comment]
I changed my mind.  I put in code to handle any non-numeric state value.  Works the same for any sensor that does that.

https://github.com/FlyingDiver/Indigo-HA-Agent/releases/tag/2023.1.1

**Comment by FlyingDiver** [comment]
Open a new issue for the boolean_input entity if needed.

**Comment by EagleDTW** [comment]
> Ok, that is the most bizarre thing I've ever seen. A DATETIME object is classified as a sensor? WTF?
> 
> But it's there, so I'll deal with it. Unfortunately, Indigo sensors can't do strings as their value. Not possible. So the best I can do is make the sensorValue the epoch value (seconds since epoch) and the UI value the data string. Should the UI value be the encoded string (2023-10-29T01:54:00+00:00) or the human formatted string (29 OCT 2023 1:54am UTC)?

Probably reporting straight through is fine, the format my script is looking for is this: '%Y-%m-%dT%H:%M:%S+00:00'
