### ISSUE TITLE
2023.1.1 close but actual state of the sensor still 0 value instead of string

### ISSUE THREAD

**Issue by EagleDTW** [FlyingDiver/Indigo-HA-Agent#6]
Hi @FlyingDiver - Joe,

2023.1.1 is close and displays in the device screen with correct value but actual state of the sensor still is passed as 0 value instead of string.

On side note there is another sensor that is empty value when nothing of note on calendar is present (like when not a holiday), and this comes up as 0.000 in device state and should just be void of any value.

Thank you,
Daniel

**Comment by EagleDTW** [comment]
Immensely appreciate you coding the evaluation copy so quickly - thanks!!

**Comment by FlyingDiver** [comment]
And it'll stay 0 because sensorValue can ONLY be a number.  Nothing I can do about it.

**Comment by FlyingDiver** [comment]
The fact that HA allows text strings as valid states for sensors is bizarre.

**Comment by EagleDTW** [comment]
So what method can I pass the text string to my script to convert the time from UTC to PST?

**Comment by EagleDTW** [comment]
It's present in some way, is there a method to grab this actual state from the device state to pass to a variable and use that variable text string in a script for converting the time?

**Comment by FlyingDiver** [comment]
> So what method can I pass the text string to my script to convert the time from UTC to PST?

https://realpython.com/python-datetime/

**Comment by FlyingDiver** [comment]
> It's present in some way, is there a method to grab this actual state from the device state to pass to a variable and use that variable text string in a script for converting the time?

Use the "actual_state" custom state in your script.  No need to go through a variable.

https://wiki.indigodomo.com/doku.php?id=indigo_2023.1_documentation:plugin_scripting_tutorial#access_a_custom_device_state

There's a specific forum on the Indigo boards for getting help with scripting.
