### ISSUE TITLE
Climate Device displays F instead of C

### ISSUE THREAD

**Issue by IndigoColly** [FlyingDiver/Indigo-HA-Agent#7]
Hi Joe.
I've added some climate devices and found that they are displaying Fahrenheit instead of Celsius. They are configured in HA with C. Let me know if there's anything I can check on my side to help.

**Comment by FlyingDiver** [comment]
Sorry, I'm a little behind on dealing with issues.

I'm pretty sure that HA works internally in F only.  Your UI might be set to C, and the values converted.  To check, enable debug logging and then look for an update for the climate device.  Is the data in F or C?  I don't do any conversions, so I would expect you'd be seeing F data.

**Comment by IndigoColly** [comment]
This is what I get:
`   Home Assistant Agent Debug      Updating device Neo Office with {'entity_id': 'climate.office_neo', 'state': 'heat_cool', 'attributes': {'hvac_modes': ['heat_cool'], 'min_temp': 5.0, 'max_temp': 35.0, 'current_temperature': 17.9, 'temperature': 17.0, 'hvac_action': 'idle', 'friendly_name': 'Office Neo', 'supported_features': 1}, 'last_changed': '2023-12-27T11:50:57.505260+00:00', 'last_updated': '2023-12-27T11:54:05.679371+00:00', 'context': {'id': '01HJNHZVFFMSW1T96XKY8HJT5A', 'parent_id': None, 'user_id': None}}
`

**Comment by IndigoColly** [comment]
It's showing 17.9F but it's actually C.

**Comment by IndigoColly** [comment]
Just to confirm... The stat is 17.9C so it's just an F v C problem in Indigo...

**Comment by FlyingDiver** [comment]
Interesting.  The update message has the value, but no units.  I'll need to see if I can get that info some other way.  If not I'll have to add it to the device config.

**Comment by FlyingDiver** [comment]
Fixed in 2023.3.2

**Comment by IndigoColly** [comment]
Updated just now, the stat shows as 17.5° with no "C" which is fine, just letting you know in case the "C" is meant to be displayed.

**Comment by FlyingDiver** [comment]
Did you go into the plugin config and select "C"?  After you do it takes until the next update from HA to change.

**Comment by IndigoColly** [comment]
Ah OK. Hadn't selected it, once I made a change to a stat it now correctly displays.
