### ISSUE TITLE
Having some weird errors and none of the devices are populating as they had just recently, any suggestions on how to fix?

### ISSUE THREAD

**Issue by EagleDTW** [FlyingDiver/Indigo-HA-Agent#9]
Hi Joe,

Having an issue with this error message when trying to pull down the list of devices for a switch:
Home Assistant Agent Error      Error in plugin execution GetUiDynamicList:

  File "plugin.py", line 305, in get_entity_list
type: ('switch',)

And having this issue when trying to update all the devices:
Home Assistant Agent Error      Error in plugin execution MenuAction:

  File "plugin.py", line 734, in get_states
  File "plugin.py", line 1073, in send_ws
type: 'NoneType' object has no attribute 'send'

I had everything working about 3 days ago and then just had to recreate my user account on my Mac do to some weirdness that apple said that account is just hosed, so Indigo DB with a fresh install to ensure that there is better conditions for all the settings in a new user account (same as old just migrated over).

Thank you,
Daniel

**Comment by EagleDTW** [comment]
Hope you had a great holiday time! Any thoughts, Joe?

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-HA-Agent/releases/tag/2023.3.1
